### ISSUE TITLE
Game crashes when attempting to open first door

### ISSUE THREAD

**Issue by Sub-Lockdown** [achiwa912/daemonlord#89]
When I attempt to enter the maze and try to open the first door of the starting room, the game crashes with the following Traceback. I am on Windows (Python 3.9.6) so I checked on a Linux sub system (Python 3.8.10), and it had the same reaction. 

`Traceback (most recent call last): `
`File "dl.py", line 6577, in <module>`
`  main()`
`File "dl.py", line 6573, in main`
`   dispatch()`
` File "dl.py", line 6308, in dispatch`
`   maze()`
`  File "dl.py", line 6250, in maze`
`   floor_obj.open_door(game, meswin)`
`TypeError: open_door() takes 2 positional arguments but 3 were given`

**Comment by achiwa912** [comment]
Thank you for the bug report.  I am not sure why there still was such a basic bug.
